### ISSUE TITLE
Empty File

### ISSUE THREAD

**Issue by pflores-bch** [sgivan/gb2ptt#1]
Hello sgivan!

I'm trying to convert a genbank file (acc: CP011849.2) to a ptt file but the outfile it's incomplete, it only recognize the number of proteins and nothing else. Also, I try to open the help command on the console and it just loop. 

I attach a screenshot about the issue. Can you lend me a hand on what i'm doing wrong??

Thank you very much!!

Patricio.

![captura de pantalla 2016-08-05 14 04 10](https://cloud.githubusercontent.com/assets/20863948/17445923/ef6463f0-5b14-11e6-9d91-f7e574f90352.png)

**Comment by sgivan** [comment]
Hi Patricio,
Can you send me the genbank input file you are using?
 Scott Givan
@sgivan

```
  From: pfloresbch <notifications@github.com>
```

 To: sgivan/gb2ptt gb2ptt@noreply.github.com 
 Sent: Friday, August 5, 2016 1:00 PM
 Subject: [sgivan/gb2ptt] Empty File (#1)

Hello sgivan!I'm trying to convert a genbank file (acc: CP011849.2) to a ptt file but the outfile it's incomplete, it only recognize the number of proteins and nothing else. Also, I try to open the help command on the console and it just loop. I attach a screenshot about the issue. Can you lend me a hand on what i'm doing wrong??Thank you very much!!Patricio.—

**Comment by pflores-bch** [comment]
Hi Scott!!

Sorry for the delay!, I was traveling. I solve the issue, it was an error on the syntaxis i was using. The correct one was $perl GBKtoPTT.pl < [yourgbkfile.gbk] > [yourdesiredoutputfile.ptt]
and I was using the same but without the "< >". 

Thank you very much anyway!!

Patricio.
